version: '3.5'
volumes:
  pgdata:
    name: pgdata

services:
  postgres:
    build:
      context: ./docker/postgres
      shm_size: 4gb
    shm_size: 4gb
    ports:
      - 5432:5432
    networks:
      - back
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'local'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  s3:
     image: minio/minio
     environment:
       - MINIO_ROOT_USER=admin
       - MINIO_ROOT_PASSWORD=admin789456123
     networks:
       - back
     command: 'server /data --console-address ":9001"'
     volumes:
       - ./db/s3:/data
     ports:
       - 9000:9000
       - 9001:9001

  s3tool:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/tools
    environment:
      - AWS_ENDPOINT=http://s3:9000
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin789456123
      - AWS_BUCKET=perimeters
    depends_on:
      - s3
    networks:
      - back

  etl:
    build:
      dockerfile: ../docker/etl/Dockerfile
      context: ./etl
    tty: true
    networks:
      - back
    depends_on:
      - postgres
    volumes:
      - ./etl:/etl
    environment:
      POSTGRES_HOST: postgres

networks:
  back: