name: 'Analysis - Lint & Test'

on:
  pull_request:
    # branches: [main]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    container: node:16.18-bullseye
    services:
      postgres:
        image: postgis/postgis:13-3.1-alpine
        env:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: apt-get update && apt-get install -y p7zip-full && yarn --frozen-lockfile
        working-directory: etl
      - name: Lint
        run: yarn lint
        working-directory: etl
      - name: Test
        run: yarn test
        working-directory: etl
        env:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: postgres
          POSTGRES_PORT: "5432"
          MIRROR_URL: https://perimeters.s3.fr-par.scw.cloud
          LOG_LEVEL: error
