name: 'Analysis - Audit dependencies'

on: pull_request

defaults:
  run:
    shell: bash

jobs:
  code-audit:
    name: Code audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn --frozen-lockfile
        working-directory: etl

      - name: 'Audit API dependencies'
        run: yarn audit --level moderate --groups dependencies && exit 0 || $([[ $? -ge 8 ]] && exit 1 || exit 0)
        working-directory: etl
