name: Publish 
on:
  release:
    types: [created]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16.18-bullseye
    steps:
      - uses: actions/checkout@v2
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: apt-get update && apt-get install -y p7zip-full && yarn --frozen-lockfile
        working-directory: etl
      - name: Build
        run: yarn build
        working-directory: etl
      - name: Publish
        run: >
          yarn config set version-git-tag false &&
          yarn publish --new-version $(git describe --tags | sed -e 's/v//') --non-interactive
        working-directory: etl
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create sources list
        run: |
          mkdir sources
          yarn source | sed '1,4d' > sources/list.txt
        working-directory: etl
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sources-list
          path: sources/list.txt
  upload_sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: upload Source list
        uses: actions/download-artifact@v3
        with:
          name: sources-list
      - name: Download missing files
        env:
          AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        run: >
          cat sources-list | docker-compose run -e AWS_ENDPOINT -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_BUCKET -T s3tool 