name: Publish 
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
       # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: apt-get update && apt-get install -y p7zip-full && yarn --frozen-lockfile
        working-directory: etl
      - name: Build
        run: yarn build
        working-directory: etl
      - name: Publish
        run: >
          yarn config set version-git-tag false &&
          yarn publish --new-version $(git describe --tags | sed -e 's/v//') --non-interactive
        working-directory: etl
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}